### ISSUE TITLE
package sets `inhibit-read-only` globally

### ISSUE THREAD

**Issue by benthamite** [armindarvish/consult-mu#29]
The functions `consult-mu--update-headers` and `consult-mu--view-msg` set the value of `inhibit-read-only` to `t` globally. As a consequence, `kill-word` and related commands have the undesirable effect of killing text even in read-only buffers. I think `inhibit-read-only` is supposed to be let-bound or set locally, rather than globally.

**Comment by armindarvish** [comment]
@benthamite should be fixed now! Let me know if there is still an issue with it.

**Comment by phil-s** [comment]
I suggest reviewing how you're using that variable in general.

I don't use this library, but I'm seeing `inhibit-read-only` let-bound at a high level initially, and then there is activity happening in *multiple* buffers with that binding in effect (which is an immediate red flag to me), and after that it's now being set buffer-locally?

I would recommend `let`-binding the variable for *only as long as you need to* in the places where it's necessary, and trying to avoid the buffer-local setting if you don't actually need that (which I think seems unlikely).

**Comment by armindarvish** [comment]
@phil-s I am imitating (and countering) what the main mu4e is (or at least was) doing. Both functions that do this are replacing (with cl-letf) a built-in function in mu4e that does use inhibit-read-only. For example;
https://github.com/djcb/mu/blob/3caa04fc2b5547611bb88022cb2aba0cc29bb894/mu4e/mu4e-headers.el#L702

since the original functions are using `inhibit-read-only`, the easiest way for me to hack this was to use the same approach to make sure every thing behaves as expected.

That said, I am not sure what the issue with using it buffer-locally is. Can you expand on why you find that dubious? This is only in the buffers for mu4e (or consult-mu) and are showing mu4e headers or messages. They are naturally read-only buffers, but when the buffers need to be updated (with a new header or new message, ...) the inhibit-read-only is set to t temporarily in a let binding. It might be possible to get rid of the line that sets the value buffer-locally (since we are doing the let-binding anyway), however from what I remember there are edge cases where the same read-only buffer would not allow updating the contents and would then block consult-mu form further updating the buffers on dynamic command updates.

So can you tell what are the concerns about setting the `inhibit-read-only` buffer-local?

**Comment by phil-s** [comment]
I don't know for certain that there's any serious problem, but I'd want to be *super* confident that there wasn't any scenario where the buffer-local value could possibly be captured and applied in another buffer.

It's definitely unexpected for it to be used for persistent effect, though.  For instance, `buffer-read-only` / `read-only-mode` has literally no effect in a buffer where `inhibit-read-only` is permanently set.

To the best of my knowledge, `inhibit-read-only` is *intended* for temporary programmatic use only.

**Comment by armindarvish** [comment]
Upon further inspection, we can just toggle the `inhibit-read-only` temporarily in a let-binding and only in the consult-mu buffers as well. This should resolve the concerns raised in the previous comments now.

If we see edge cases that have issues we can address them separately later.
